### ISSUE TITLE
Friction 1.0.0 Roadmap

### ISSUE THREAD

**Issue by rodlie** [friction2d/friction#142]
This issue tracks the progress of [v1.0.0](https://github.com/friction2d/friction/milestone/10).

- [x] **Beta 1 - 16 October (core feature freeze)**
- [x] **Beta 2 - 2 December (functional feature freeze)**
- [ ] **Release Candidate - Early December**
- [ ] **Release - Mid to late December**

**Comment by rodlie** [comment]
Will do a beta release shortly after the release of 0.9.6.1 (#202), probably this weekend.

**Comment by rodlie** [comment]
And... I missed the deadline again.

Anyway, the plan now is to release v0.9.6.1 on Friday and v1.0.0-beta1 on Sunday.

*Note that anything may happen, but this is my goal for the week.*

### Todo for the week

* Try to finish the HiDPI changes in v1 I started a couple of days ago
* Get working Linux CI that produces downloadable v1 builds (already added for Windows)
* Theme adjustments for v1
* Update release notes for v1 with new features (screenshots/videos)
* Produce release builds for v0.9.6.1

End the week with v1.0.0-beta1 release.

**Comment by eFe-Munoz** [comment]
That's good news!

**Comment by rodlie** [comment]
So, timeline for release(s) will look something like this:

* **Release** `v1.0.0-beta1` *(ETA a couple of days after `v0.9.6.1` release)*
* **Release** `v1.0.0-beta2` *(ETA Early September)*
  * If we have important fixes that also apply to the `v0.9` branch do a `v0.9.6.2` release with backports
* **Release** `v1.0.0-rc1` *(ETA Late September/Early October)*
  * If we have important fixes that also apply to the `v0.9` branch do a `v0.9.6.3` release with backports
* **Release** `v1.0.0-rc2` if needed
* **Release** `v1.0.0`  *(ETA Late October/Early November)*
 
"best-case scenario™" :smile:

I will try to release `v0.9.6.1`  today, but I might just do a quick RC1 and do the final release on Sunday. Don't know yet.

**Comment by eFe-Munoz** [comment]
Great news!

**Comment by eugenialoli** [comment]
Love it, hope you also include a light theme, because I have an eye condition that i can't read well in dark backgrounds. Also, it would be useful to also create a flatpak (and maybe a snap) for the beta version, because that's how you're going to get exposure and people will be able to find bugs to be fixed for the final 1.0 version. Flatpak is where it's at these days for exposure... plus maybe the phoronix website.

**Comment by rodlie** [comment]
Hi Eugenia

> hope you also include a light theme

Not for v1. It's hard enough to maintain one theme across platforms. But this is something I can look at in a later release (1.1/1.2).

> create a flatpak

To be honest I don't care about all the packaging formats out there. I produce one quality binary bundle that work on anything, that's my priority. I also only support the release binaries. Custom builds, distro builds etc are not supported (for obvious reasons).

It's however simple for someone to repack the release binaries into a flatpak, so if anyone want's to maintain the flathub script let me known and we will make it official.

> how you're going to get exposure

Yeah, not my highest priority. I could generate a lot more attention and exposure if I wanted to, but that will just generate more "noise". The more users the more work for me.

At the end of the day this is a tool I and others use at work, nothing else. I only maintain it in that context, in my spare time.

This project has the potential to go places, but then I would have to work full-time on this project, and I don't work for free ;)

I may sound a bit negative, this is not my intent :)

**Comment by eFe-Munoz** [comment]
Greetings.

Do you know the release date of BETA 1.0?

**Comment by rodlie** [comment]
So, we are now in a feature freeze, any feature requests or features in development will be pushed to next release (v1.1).

I will use a couple of days to iron out any issues introduced and clean up remaining UI/UX stuff then do a beta release. I aim to do a final release by the end of October.

After release of the beta I will try to resolve some of the open bug issues we have.

---

We have functional CI for both Windows and Linux, so anyone can test the `main` branch, no need to wait on a release.

* https://github.com/friction2d/friction/actions/workflows/windows.yml
* https://github.com/friction2d/friction/actions/workflows/linux.yml

Select a commit, scroll down and download zip file.

I have also created simplified url's:

* https://windows.ci.friction.graphics - will give you the latest Windows build from `main`
* https://linux.ci.friction.graphics - will give you the latest Linux build from `main` *(I just added this, so there might be a DNS delay)*

**Comment by eFe-Munoz** [comment]
Good news: What is an IC?

Do you need a performance report?

**Comment by rodlie** [comment]
The snapshots includes portable and installer, note that the portable is actually portable now, settings etc are contained in the folder you run Friction from.

I don't need any reports yet, I will concentrate on finishing UI stuff and make sure the new stuff works "good enough", also need to write release notes, docs etc.

**Comment by eFe-Munoz** [comment]
The Timeline and the effects menu look great.
Just a question, has the UI scaling disappeared in the configuration? On large monitor (like mine) the icons look tiny.

**Comment by rodlie** [comment]
> has the UI scaling disappeared in the configuration? On large monitor (like mine) the icons look tiny.

Ahh, yes. I improved hdpi on Windows and the setting didn't seem to fix/do anything on my setup, so I disabled it. But if it's not the case I will figure out something else.

What resolution are you using and are you using display scaling (if so how much)? A screenshot could also help.

**Comment by eFe-Munoz** [comment]
This is how I see it now (beta 1):
![imagen](https://github.com/user-attachments/assets/a90a1b89-deba-4027-bf66-be661da8f9b6)

And this is how I see it in version 0.9.6.1 at 150%:
![imagen](https://github.com/user-attachments/assets/9052bf27-0785-4c9c-bf6e-af704f22a0dc)

**Comment by rodlie** [comment]
you set Friction 0.9 to 150% or the display?

**Comment by eFe-Munoz** [comment]
Yes, because the resolution of my monitor is about 150 dpi, not 72 dpi (as they usually are) and that makes everything smaller.

**Comment by rodlie** [comment]
Ok, try this build when done (will take ~13min to build): https://github.com/friction2d/friction/actions/runs/11105014852

Didn't have the time to test on Windows, but should bring back scaling override.

**Comment by eFe-Munoz** [comment]
Hi, I have installed the version, I rescale UI to 150% it tells me to reboot and when I reboot it keeps scaling to 100%.

**Comment by rodlie** [comment]
Works fine on my setup (Win11 laptop with 1920x1080).

### Windows Scaling 100% - Friction Scaling Auto
![friction1-win11-display-100-friction-auto](https://github.com/user-attachments/assets/5b3b5f1c-5e41-4f8b-add0-e01eb14e5fe0)

### Windows Scaling 100% - Friction Scaling 150%
![friction1-win11-display-100-friction-150](https://github.com/user-attachments/assets/9624605d-fe2d-4567-a3a3-ce89b046bbdb)

### Windows Scaling 125% - Friction Scaling Auto
![friction1-win11-display-125-friction-auto](https://github.com/user-attachments/assets/a2d0ae41-19a9-4b5d-9340-6f859fc64c82)

### Windows Scaling 150% - Friction Scaling Auto
![friction1-win11-display-150-friction-auto](https://github.com/user-attachments/assets/8c33d4bd-f627-4e11-8cd3-60dd566accdc)

---

Everything looks as expected.

**Comment by rodlie** [comment]
Also tested on my Windows 10 workstation using a ProArt 4k, works fine there as well. Some icons with Windows scaling set to 200% on 4k look a bit stretched, but there are limits to what I care to support/test.

Setting scaling in Friction also works fine here.

### Windows 100% - Friction 150%
![friction1-win10-windows-100-friction-150-proart24-4k](https://github.com/user-attachments/assets/79bb893e-9664-40b2-8b7d-3be23cabfe1f)

**Comment by eFe-Munoz** [comment]
ok I must have the wrong version.

![imagen](https://github.com/user-attachments/assets/23aa37e8-4d27-433a-849d-6063c7f2350f)

**Comment by rodlie** [comment]
[9f3055e](https://github.com/friction2d/friction/commit/9f3055ebf8ed5c8bc45047e2616fd5f505c255ec)  is the correct version (or newer). The warning you get is because something is wrong with the dpi, what is the detected font size in the warning?

**Comment by eFe-Munoz** [comment]
I downloaded and installed that version and scaling the UI still doesn't change anything. Neither the reboot.

![imagen](https://github.com/user-attachments/assets/ceb8dc74-5542-4d3d-be94-d98394f5c2aa)

![imagen](https://github.com/user-attachments/assets/3dd9154c-4537-4aa7-8308-ffe5b82e7494)

**Comment by rodlie** [comment]
Not able to replicate.

**Comment by eFe-Munoz** [comment]
Ok, I got it! the secret was that “Auto” was active and the changes did not take effect. Everything is fine now.

![imagen](https://github.com/user-attachments/assets/b245b331-cbba-4871-8caa-c4ae34f17ac6)

![imagen](https://github.com/user-attachments/assets/9949dc3c-034d-493e-8f54-fee57f1fc25e)

**Comment by rodlie** [comment]
Good :+1: 

I was supposed to ask you about that yesterday, but forgot.

**Comment by rodlie** [comment]
Should probably disable the slider if auto is enabled, will add it later today.

**Comment by eFe-Munoz** [comment]
Maybe, yes.

**Comment by rodlie** [comment]
Done, slider is disabled if 'auto'.

**Comment by rodlie** [comment]
Will try to release v1.0 beta tomorrow, depends on how my internal testing goes today (win 10/11, intel/nvidia, linux rpm/portable/appimage etc). Been using v1.0/main at work for a couple of weeks now.

Also need to write release notes, unsure if I'm able to finish them today, a lot of changes has happened and I'm not even sure I remember all of them. Worst case the release notes will be very simplified compare to final.

**Comment by eFe-Munoz** [comment]
Ok, here's an example.

I import an image and I want to align and animate it according to its base. But when I create an object or import a file its default axis is in the center (example image):
![imagen](https://github.com/user-attachments/assets/c0d9b3ef-f09b-405a-ad23-f259c67d91ba)

It would be great if in the alienation options you could alienate the pivot with respect to the dimensions of the object/image. This way you could easily place the axis of an object/image on the base in the center without having to do it by hand and not very precisely.
![imagen](https://github.com/user-attachments/assets/6099ffa8-a4a4-4d31-a6da-85dfd5c32732)
It would thus be aligned at the bottom center. Other times it is necessary to align top right or center left...
![imagen](https://github.com/user-attachments/assets/6eae9d5b-2854-47f5-8466-446982c4675c)

**Comment by rodlie** [comment]
Did some updates to the release schedule (see first post). Expect a beta 2 release by the end of next week. Then RC(s) and final release in November.

We are generally in good shape, but I want some extra time for testing/QA etc.

**Comment by eFe-Munoz** [comment]
Very much looking forward...

**Comment by rodlie** [comment]
Delays, delays, delays ... :smile: 

Ok, Beta 2 is now scheduled for Saturday (30 November).

**This will be a hard feature freeze, whatever feature is not done by Friday will not be part of v1.0.x.**

**Comment by rodlie** [comment]
Closing this.

We will skip Beta 3 and go directly to RC1, with a goal to get it out within a week(ish), then try to fix open bugs for the 1.0 milestone and finish the first draft of the documentation, then release 1.0.0.
