### ISSUE TITLE
Friction 0.9.6.1 Roadmap

### ISSUE THREAD

**Issue by rodlie** [friction2d/friction#202]
- [ ] [Release Notes](https://github.com/friction2d/friction2d.github.io/blob/main/_drafts/friction-0961.md)
- [ ] Build source release
- [ ] Build Windows release
- [ ] Build Linux release
- [ ] Update website

**Comment by rodlie** [comment]
Snapshot build https://sourceforge.net/projects/friction/files/0.9.6.1-47660298/

**Comment by rodlie** [comment]
ETA for release is 2024-07-24.
