### ISSUE TITLE
Release v0.9.2

### ISSUE THREAD

**Issue by rodlie** [friction2d/friction#33]
### Roadmap

List of features/changes planned for [v0.9.2](https://github.com/friction2d/friction/milestone/3).

- [x] #31 
- [x] #32 
- [x] #6 
  - [x]  Various changes
  - [x] Remove SwitchButton
- [x] Many bugfixes 

### Release tasks

- [x] Test, test, test
- [x] Write release notes
- [x] Update build scripts 
- [x] Build
  - [x] Ubuntu 22.04
  - [x] Ubuntu 23.04
  - [x] Fedora 38
  - [x] RHEL 9
  - [x] Windows 10
