### ISSUE TITLE
Roadmap v0.9.4

### ISSUE THREAD

**Issue by rodlie** [friction2d/friction#34]
List of features/changes planned for [v0.9.4](https://github.com/friction2d/friction/milestone/5).

- [ ] #28
- [ ] hidpi support for icons is needed (setIconSize), depends on #3 
- [ ] #3 
  - [ ] Finish the migration to QIcon::fromTheme
  - [ ] Remove "legacy" code related to icons
