### ISSUE TITLE
Track friction in downstream package ecosystem

### ISSUE THREAD

**Issue by luzpaz** [friction2d/friction#76]
### Current Snapshot of Friction in package ecosystem

<a href="https://repology.org/project/friction/versions">
    <img src="https://repology.org/badge/vertical-allrepos/friction.svg?columns=3&header=Friction%20Package%20Status&exclude_unsupported=1" alt="Packaging status">
</a>

### TODO

- [ ] Alpine Linux
- [ ] Arch Linux
- [ ] FreeBSD https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=273616
- [ ] Gentoo https://bugs.gentoo.org/913756
- [ ] chocolatey https://github.com/chocolatey-community/chocolatey-package-requests/issues/1449
- [ ] OpenMandriva https://github.com/OpenMandrivaAssociation/distribution/issues/3011
- [x] winget https://github.com/microsoft/winget-pkgs/issues/119024

**Comment by rodlie** [comment]
Also note that I have signed up Friction as a publisher on the Microsoft Store, will (try to) publish Friction on the store for the next release.

**Comment by luzpaz** [comment]
Winget has added friction.

**Comment by rodlie** [comment]
Nice :+1:

**Comment by luzpaz** [comment]
* bumped winget, hopefully they'll update to beta2
* freebsd closed the ticket request

**Comment by luzpaz** [comment]
> Should they? I assume they offer latest stable (0.9.6.1).

Good point. I just altered request to bump to latest stable.

**Comment by rodlie** [comment]
Not the end of the world if they offer beta's, v1.0 stable will be done by the end of the month.

Regarding distros:

Friction currently needs specific versions of various dependencies to work properly and the various distros will not be able to offer them, and as such they will always offer a inferior version of Friction. Something I really don't want, it means more bug reports not related to Friction.

IMHO I think we should just offer an official flatpak (together with the other binaries we have), most distro support/use flatpak.

**Comment by luzpaz** [comment]
> Something I really don't want, it means more bug reports not related to Friction.

It's true.. and I hear that. On the other hand, it also gets the word out about Friction when downstream repos offer it. It becomes inevitable either way if Friction gets popular.

**Comment by rodlie** [comment]
> On the other hand, it also gets the word out about Friction when downstream repos offer it

Yeah, I understand that, but it's not important to me. Your random Linux user is not the target audience. "Getting the word out" means reaching out to the target users, animators, designers etc. Through social media, forums, (review) websites etc.

Currently this happens "organically" through word of mouth. This could be improved, but I have not put any effort into it (we have a bluesky/mastodon profile where I post releases), as more users means more work/noise for me ;) *(no disrespect to any users)*

As long as this is a (unpaid) spare time project I don't want too much attention. This project exist to make my job easier, not consume my spare time in return ;)

**Comment by luzpaz** [comment]
Fair. I will respect your wishes. Closing this ticket, ITC.

**Comment by rodlie** [comment]
We will submit Friction to Flathub after v1.0.0 release. Let's keep this open to track that and snap (Ubuntu is Ubuntu, can't do much than just support it).

Since flatpak is getting more popular (RHEL 10 now only supports flatpaks) , it has a good chance of becoming the "universal" package manager on the Linux desktop, I think we should go "all-in" on that.

I have fixed wayland+portal support and Friction seems to work as it should, I'm dogfooding Friction through flatpak at the moment.

Initial documentation: https://friction.graphics/documentation/flatpak.html

Since our universal binary now works on anything the maintenance for flatpak and (when the time comes) snap etc is minimal.

**Comment by luzpaz** [comment]
Note: I've fixed the repology badge. They renamed the package to `friction-motion-graphics` to disambiguate from other 'fiction'-named applications.

**Comment by luzpaz** [comment]
Added link to the nixOS PR which is stalled ATM.

**Comment by rodlie** [comment]
FYI... Flatpak will be the main focus on Linux going forward. We will still offer AppImages (ease of testing etc), but after the v1.0.0 release the prefered way to use Friction on Linux will be through Flatpak.

- One target platform
- Less maintenance
- Default for GUI apps on several distros

Yes, Flatpak may have it's issues, but at the moment it's the best we got in terms of a unified packaging system.

I will submit a PR soon that supports full sandboxing:
```
flatpak info --show-permissions graphics.friction.Friction/x86_64/master
[Context]
shared=ipc;
sockets=x11;wayland;pulseaudio;fallback-x11;
devices=dri;
filesystems=

[Session Bus Policy]
com.canonical.AppMenu.Registrar=talk
```

Also, we will add support for Qt6 (and modern ffmpeg) shortly after the release of v1.0.0. I assume more distros will package Friction when that happens.
